# pdf-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-worker
spec:
  selector:
    matchLabels:
      app: pdf-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: pdf-worker
    spec:
      containers:
        - name: pdf-worker
          image: deployment-risks-pdf-worker
          imagePullPolicy: Never
          command: ["node", "src/workers/pdfWorker.js"]
          env:
            - name: NODE_ENV
              value: "development"
            - name: DATABASE
              value: "mongodb://mongo:27017/local-idurar-erp-crp"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: PDF_OUTPUT_DIR
              value: "/usr/src/app/pdf-storage"
          volumeMounts:
            - name: pdf-storage
              mountPath: /usr/src/app/pdf-storage
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: pdf-storage
          persistentVolumeClaim:
            claimName: pdf-storage-pvc